### ISSUE TITLE
rack_server example problem

### ISSUE THREAD

**Issue by timhatch** [digital-fabric/tipi#11]
I had to switch away from testing Tipi for a while, but started to look at the rack_server examples in more detail this weekend.

The basic example using `hello.ru` as the config file works without issue (Invoked via `bundle exec ruby ./rack_server ./hello.ru`)

The Cuba example, again running `rack_server.rb` but with `cuba.ru` as the config file runs, but routing doesn't seem work. I didn't check the hanami_api.ru example, as I'd already tried some quick tests to see if other simple rack apps (sinatra, roda) had the same issue, which they did.

Could you take a quick look? Not at all sure what the cause is.

**Comment by ciconia** [comment]
Thanks for reporting this. Please note that the most of the Rack adapter code (i.e. dealing with the Rack env) has been moved to https://github.com/digital-fabric/qeweney. See also #4.

**Comment by timhatch** [comment]
No problem. I'll hopefully be able to test it out in the next few days. The performance of the tipi server looks awesome!

**Comment by ciconia** [comment]
> The performance of the tipi server looks awesome!

I've started work on a [custom HTTP/1 parser](https://github.com/digital-fabric/tipi/blob/master/ext/tipi/http1_parser.c) (and eventually also one for HTTP/2) for Tipi that will improve performance even more!
