### ISSUE TITLE
Benchmarks or comparison with Puma and friends?

### ISSUE THREAD

**Issue by mensfeld** [digital-fabric/tipi#12]
Hey there, in your docs you state:

```
Polyphony, a robust, high-performance library for building highly-concurrent applications in Rub
```

Do you have any benchmarks to compare this with others?

Thanks!

**Comment by ciconia** [comment]
Thank you for your suggestion. I have added some benchmark results in the [README](https://github.com/digital-fabric/tipi#benchmarks). I intend to create a tool to generate those results automatically at some point in the future.

**Comment by mensfeld** [comment]
Thank you. Looking forward to seeing this project grow!
