### ISSUE TITLE
Supervision for websocket + Qeweney setup

### ISSUE THREAD

**Issue by dm1try** [digital-fabric/tipi#17]
I'm not sure how to properly use [supervision](https://github.com/digital-fabric/tipi#worker-process-supervision) when we have a websocket handler and Qeweney handler.
see https://github.com/dm1try/wordle/blob/main/app.rb#L19-L107 for example. is it possible?

Thanks!

**Comment by ciconia** [comment]
The process supervision mechanism has nothing to do with your app. If you want to run your app locally just run `tipi -l localhost:1234 app.rb`. Let me know if you run into any problems. :-)

**Comment by dm1try** [comment]
@ciconia thank you for the reply, I want to run it locally but also want to use supervising and maybe apply  graceful restarts(hot code reloading).

so it looks like I can setup it like so https://github.com/digital-fabric/tipi/blob/da9a76d8f96e1319c60daef5841c761708ae30b8/examples/hello.rb#L1-L5

and in this case I can send `USR2` signal to the supervisor pid. but how should I configure a websocket hander?


why I'm asking all of this, with the current setup I receive some errors that put the server down:
```
/404/index.html
{}
/home/deploy/wordle/shared/vendor/bundle/ruby/2.7.0/gems/qeweney-0.16/lib/qeweney/routing.rb:10:in `route': undefined method `split' for nil:NilClass (NoMethodError)
	from /home/deploy/wordle/shared/vendor/bundle/ruby/2.7.0/gems/tipi-0.47/lib/tipi.rb:63:in `block in route'
	from /home/deploy/wordle/shared/vendor/bundle/ruby/2.7.0/gems/tipi-0.47/lib/tipi/http1_adapter.rb:57:in `handle_request'
	from /home/deploy/wordle/shared/vendor/bundle/ruby/2.7.0/gems/tipi-0.47/lib/tipi/http1_adapter.rb:28:in `each'
	from /home/deploy/wordle/shared/vendor/bundle/ruby/2.7.0/gems/tipi-0.47/lib/tipi.rb:50:in `client_loop'
	from /home/deploy/wordle/shared/vendor/bundle/ruby/2.7.0/gems/tipi-0.47/lib/tipi.rb:41:in `block (2 levels) in accept_loop'
Controller has terminated with status: 1
Detected dead controller. Restarting...
```

The controller hadn't restarted at such case even if we see "Restarting..." here

**Comment by ciconia** [comment]
OK, I think I understand now. You can manually upgrade plain HTTP to WebSocket as follows:

```ruby
app = ->(req) do
  if req.upgrade_protocol == 'websocket'
    conn = req.upgrade_to_websocket
    my_ws_handler(conn)
  else
    req.respond(HTML, 'Content-Type' => 'text/html')
  end
end
```

Also, note that the whole supervision/restart mechanism is currently flakey. I did some work in the last few days on improving signal handling in Polyphony, but I still need to spend some time on working out some issues I've been having with the Tipi supervisor/controller mechanism.

**Comment by ciconia** [comment]
As for the error you're getting, please give me a minimal app that shows the error (and the URL that generates the error) so I can investigate.

**Comment by dm1try** [comment]
> You can manually upgrade plain HTTP to WebSocket as follows:

@ciconia thanks, it's very helpful

> Also, note that the whole supervision/restart mechanism is currently flakey. I did some work in the last few days on improving signal handling in Polyphony, but I still need to spend some time on working out some issues I've been having with the Tipi supervisor/controller mechanism.

I see, I'll try to think about some other strategies but also will check hot it works now :) 


> As for the error you're getting, please give me a minimal app that shows the error (and the URL that generates the error) so I can investigate.

in the trace above you can see the url and query params
```ruby
puts r.path
puts r.query
```
but I looks like there is nothing suspicious.

I've added some more logging, let's see if it helps. the cause of such behavior is crawling by some bots, maybe I'll put the app behind nginx later. 
anyway I'll create a separate issue for the error if I collect more information.

Thanks again for the fast responses!
